#!/bin/bash
SDK_VERSION=dev
set -u # break on undefined vars.
cd "$(dirname "$0")" || exit 1
APP="$(basename "$0")"
echo "Self-deploying APP=$APP ENV=$ENV VERSION=$VERSION..." >&2
must git clone --depth=1 -b "$SDK_VERSION" --single-branch \
	git@github.com:allegory-software/allegory-sdk  sdk
must git clone --depth=1 -b "$SDK_VERSION" --single-branch \
	git@github.com:allegory-software/allegory-sdk-bin-debian10  sdk/bin/linux
cat << EOF > ${APP}.conf
deploy    = '$DEPLOY'
env       = '$ENV'
version   = '$VERSION'
db_schema = '$MYSQL_SCHEMA'
db_user   = '$MYSQL_USER'
db_pass   = '$MYSQL_PASS'
secret    = '$SECRET'
log_host  = '127.0.0.1'
log_port  = 5555
EOF
